eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.106.251:8761/eureka/
    
instance:
  prefer-ip-address:true
  ip-address:106.13.106.251
  
server:
  port: 8763

spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://106.13.106.251:3306/eshop
    username: root
    password: Abcd1234%